(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(avy-background t)
 '(ccm-recenter-at-end-of-file nil)
 '(package-selected-packages
   '(org-brain dashboard xterm-title html-mode prettier-js typescript-mode auto-compile gcmh git-timemachine highlight-numbers hl-todo lsp-ui lsp-mode flycheck smex counsel-projectile projectile counsel company general evil-easymotion avy graphql-mode yaml-mode json-mode which-key evil-surround evil-collection evil-terminal-cursor-changer evil use-package no-littering))
 '(paradox-github-token t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-candidate-face ((t (:inherit popup-face :background "black" :foreground "#073642"))))
 '(ac-completion-face ((t (:foreground "color-239" :underline nil))))
 '(ac-selection-face ((t (:inherit popup-menu-selection-face :background "black" :foreground "#2aa198"))))
 '(avy-background-face ((t (:foreground "#525252"))))
 '(avy-lead-face ((t (:background "inherit" :foreground "red" :weight bold))))
 '(avy-lead-face-0 ((t (:inherit avy-lead-face :background "inherit" :foreground "#FF6666"))))
 '(avy-lead-face-1 ((t (:inherit avy-lead-face :background "brightblack" :foreground "black"))))
 '(avy-lead-face-2 ((t (:inherit avy-lead-face :background "inherit" :foreground "#FF9999"))))
 '(company-echo-common ((t (:foreground "blue"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "blue"))))
 '(company-scrollbar-bg ((t (:inherit tooltip :background "black"))))
 '(company-scrollbar-fg ((t (:background "cyan"))))
 '(company-tooltip ((t (:inherit tooltip :background "black" :foreground "white"))))
 '(company-tooltip-annotation ((t (:foreground "yellow"))))
 '(company-tooltip-common ((t (:foreground "blue"))))
 '(company-tooltip-selection ((t (:background "brightblack" :foreground "brightcyan" :weight bold))))
 '(counsel-variable-documentation ((t (:inherit nil))))
 '(doom-modeline-bar-inactive ((t nil)))
 '(doom-modeline-battery-normal ((t (:inherit mode-line :background "black" :weight normal))))
 '(doom-modeline-debug-visual ((t (:background "#073642"))))
 '(error ((t (:foreground "red" :weight bold))))
 '(fill-column-indicator ((t (:inherit shadow :stipple nil :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
 '(flycheck-error ((t (:underline t))))
 '(flycheck-info ((t (:underline t))))
 '(flycheck-warning ((t (:background "red" :foreground "white" :underline (:color "#ECBE7B" :style wave)))))
 '(font-lock-comment-face ((t (:foreground "#525252" :slant italic))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "color-239"))))
 '(font-lock-function-name-face ((t (:foreground "brightcyan"))))
 '(font-lock-string-face ((t (:foreground "magenta"))))
 '(font-lock-type-face ((t (:foreground "magenta"))))
 '(font-lock-variable-name-face ((t (:foreground "blue"))))
 '(highlight ((t (:background "color-89" :foreground "black"))))
 '(highlight-blocks-depth-1-face ((t (:background "black"))))
 '(highlight-indent-guides-character-face ((t (:foreground "black"))))
 '(highlight-indent-guides-even-face ((t (:foreground "black"))))
 '(highlight-indent-guides-odd-face ((t (:foreground "brightgreen"))))
 '(highlight-numbers-number ((t (:inherit font-lock-constant-face :foreground "yellow"))))
 '(hl-line ((t (:background "black"))))
 '(indent-guide-face ((t (:inherit hl-line :background "brightblack" :foreground "black"))))
 '(ivy-current-match ((t (:extend t :background "color-25" :foreground "white"))))
 '(ivy-minibuffer-match-face-1 ((t (:background "magenta" :foreground "black"))))
 '(ivy-minibuffer-match-face-2 ((t (:background "color-125" :foreground "black" :weight bold))))
 '(ivy-minibuffer-match-face-3 ((t (:background "#7777ff" :foreground "black" :weight bold))))
 '(ivy-separator ((t (:inherit nil))))
 '(ivy-virtual ((t (:inherit nil :foreground "#ddd"))))
 '(line-number ((t (:inherit default :foreground "yellow" :strike-through nil :underline nil :slant normal :weight normal))))
 '(line-number-current-line ((t (:background "brightblack" :foreground "yellow" :strike-through nil :underline nil :slant normal :weight normal))))
 '(linum ((t (:inherit default :foreground "#a9a1e1" :strike-through nil :underline nil :slant normal :weight normal))))
 '(lsp-face-highlight-read ((t (:background "color-25" :foreground "#dfdfdf" :weight bold))))
 '(lsp-face-highlight-textual ((t (:inherit highlight :background "color-25" :foreground "#dfdfdf" :weight bold))))
 '(lsp-ui-doc-background ((t (:inherit tooltip))))
 '(lsp-ui-peek-filename ((t (:inherit mode-line-buffer-id :background "black"))))
 '(lsp-ui-peek-footer ((t (:inherit lsp-ui-peek-header :background "black"))))
 '(lsp-ui-peek-header ((t (:background "black" :foreground "#bfbfbf" :weight bold))))
 '(lsp-ui-peek-list ((t (:background "black"))))
 '(lsp-ui-peek-peek ((t (:background "black"))))
 '(lsp-ui-peek-selection ((t (:background "black" :foreground "cyan" :weight bold))))
 '(mode-line ((t (:background "black" :foreground "#bfbfbf" :box nil))))
 '(mode-line-inactive ((t (:background "black" :foreground "#525252" :box nil))))
 '(popup-scroll-bar-background-face ((t (:background "black"))))
 '(popup-scroll-bar-foreground-face ((t (:background "brightyellow"))))
 '(region ((t (:extend t :background "color-248" :foreground "black"))))
 '(rust-unsafe-face ((t (:inherit font-lock-error-face :foreground "brightred"))))
 '(show-paren-match ((t (:background "black" :foreground "#ff6655"))))
 '(warning ((t (:foreground "yellow" :weight bold))))
 '(window-divider ((t (:inherit nil :background "black" :foreground "black")))))


